# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='orator',
    version='0.9.9',
    description='The Orator ORM provides a simple yet beautiful ActiveRecord implementation.',
    python_requires='!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<4.0,>=2.7',
    project_urls={
        "homepage": "https://orator-orm.com/",
        "repository": "https://github.com/sdispater/orator"
    },
    author='Sébastien Eustace',
    author_email='sebastien@eustace.io',
    license='MIT',
    keywords='database orm',
    entry_points={
        "console_scripts": [
            "orator = orator.commands.application:application.run"
        ]
    },
    packages=[
        'orator', 'orator.commands', 'orator.commands.migrations',
        'orator.commands.models', 'orator.commands.seeds', 'orator.connections',
        'orator.connectors', 'orator.dbal', 'orator.dbal.exceptions',
        'orator.dbal.platforms', 'orator.dbal.platforms.keywords',
        'orator.dbal.types', 'orator.events', 'orator.exceptions',
        'orator.migrations', 'orator.orm', 'orator.orm.mixins',
        'orator.orm.relations', 'orator.orm.scopes', 'orator.pagination',
        'orator.query', 'orator.query.grammars', 'orator.query.processors',
        'orator.schema', 'orator.schema.grammars', 'orator.seeds',
        'orator.support', 'orator.utils'
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'backpack==0.*,>=0.1.0', 'blinker==1.*,>=1.4.0', 'cleo==0.*,>=0.6.0',
        'faker==0.*,>=0.8.0', 'inflection==0.*,>=0.3.0',
        'lazy-object-proxy==1.*,>=1.2.0', 'pendulum==1.*,>=1.4.0',
        'pyaml==16.*,>=16.12.0', 'pygments==2.*,>=2.2.0', 'pyyaml==5.*,>=5.1.0',
        'simplejson==3.*,>=3.10.0', 'six==1.*,>=1.10.0', 'wrapt==1.*,>=1.10.0'
    ],
    extras_require={
        "dev": [
            "flexmock==0.9.7", "pre-commit==1.*,>=1.11.0",
            "pytest==3.*,>=3.5.0", "pytest-mock==1.*,>=1.6.0",
            "tox==3.*,>=3.5.0"
        ],
        "mysql": ["mysqlclient==1.*,>=1.3.0"],
        "mysql-python": ["pymysql==0.*,>=0.7.0"],
        "pgsql": ["psycopg2==2.*,>=2.7.0"]
    },
)
